name: PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: 
        pod install --repo-update --clean-install --project-directory=CardFlip/
        xcodebuild clean test -project CardFlip.xcodeproj -scheme CardFlip -destination "platform=iOS Simulator,name=iPhone 11 Pro"
