name: PR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: 
        pod install --repo-update --clean-install --project-directory=thereto-ios/
        xcodebuild test -workspace thereto-ios/thereto-ios.xcworkspace -scheme thereto-ios -destination 'platform=ios Simulator, name=iPhone 11 Pro,OS=13.6'
